export const BOOKING_LIST_MY_REQUEST = "BOOKING_LIST_MY_REQUEST";
export const BOOKING_LIST_MY_SUCCESS = "BOOKING_LIST_MY_SUCCESS";
export const BOOKING_LIST_MY_FAIL = "BOOKING_LIST_MY_FAIL";

export const BOOKING_DETAILS_REQUEST = "BOOKING_DETAILS_REQUEST";
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL"

export const BOOKING_PAY_REQUEST = "BOOKING_DELETE_REQUEST";
export const BOOKING_PAY_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const BOOKING_PAY_FAIL = "BOOKING_DELETE_FAIL";
export const BOOKING_PAY_RESET = "BOOKING_DELETE_RESET";

export const BOOKING_CREATE_REQUEST = "BOOKING_CREATE_REQUEST";
export const BOOKING_CREATE_SUCCESS = "BOOKING_CREATE_SUCCESS";
export const BOOKING_CREATE_FAIL = "BOOKING_CREATE_FAIL";
