export const ROOM_LIST_REQUEST = 'ROOM_LIST_REQUEST';
export const ROOM_LIST_SUCCESS = 'ROOM_LIST_SUCCESS';
export const ROOM_LIST_FAIL = 'ROOM_LIST_FAIL';
export const ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST';
export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL';
export const SEARCH_ROOMS_SUCCESS = 'SEARCH_ROOMS_SUCCESS';
export const SEARCH_ROOMS_FAIL = 'SEARCH_ROOMS_FAIL';
export const ROOM_SEARCH_SUCCESS = 'ROOM_SEARCH_SUCCESS';
export const SEARCH_ROOMS_REQUEST = 'SEARCH_ROOMS_REQUEST';
export const ROOM_SEARCH_FAIL = 'ROOM_SEARCH_FAIL';
export const ROOM_SEARCH_REQUEST = 'ROOM_SEARCH_REQUEST';

