# Generated by Django 5.1.5 on 2025-01-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("numReviews", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
