# Generated by Django 5.1.5 on 2025-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
