# Generated by Django 5.1.5 on 2025-03-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_booking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='total_price',
        ),
    ]
