# Generated by Django 5.1.5 on 2025-03-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_amenity_room_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.policy'),
        ),
    ]
