# Generated by Django 5.1.5 on 2025-03-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_chatroom_buyer_remove_chatroom_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='lister',
        ),
    ]
