# Generated by Django 5.1.5 on 2025-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_host_alter_room_image_alter_room_lister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
    ]
