# Generated by Django 5.1.5 on 2025-03-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_room_host'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user', 'host')},
        ),
    ]
